"use strict";(self.webpackChunkdocs=self.webpackChunkdocs||[]).push([[367],{4863:(e,r,o)=>{o.r(r),o.d(r,{assets:()=>d,contentTitle:()=>s,default:()=>l,frontMatter:()=>i,metadata:()=>c,toc:()=>a});var t=o(5893),n=o(1151);const i={sidebar_position:60},s="Error handling",c={id:"errors",title:"Error handling",description:"isErrorWithCode(value)",source:"@site/docs/errors.md",sourceDirName:".",slug:"/errors",permalink:"/docs/errors",draft:!1,unlisted:!1,tags:[],version:"current",sidebarPosition:60,frontMatter:{sidebar_position:60},sidebar:"guidesSidebar",previous:{title:"Jest module mocks",permalink:"/docs/jest-mocks"},next:{title:"License",permalink:"/docs/license"}},d={},a=[{value:"<code>isErrorWithCode(value)</code>",id:"iserrorwithcodevalue",level:3},{value:"Error codes",id:"error-codes",level:3}];function h(e){const r={a:"a",code:"code",h1:"h1",h3:"h3",p:"p",pre:"pre",table:"table",tbody:"tbody",td:"td",th:"th",thead:"thead",tr:"tr",...(0,n.a)(),...e.components};return(0,t.jsxs)(t.Fragment,{children:[(0,t.jsx)(r.h1,{id:"error-handling",children:"Error handling"}),"\n",(0,t.jsx)(r.h3,{id:"iserrorwithcodevalue",children:(0,t.jsx)(r.code,{children:"isErrorWithCode(value)"})}),"\n",(0,t.jsxs)(r.p,{children:["TypeScript helper to check if the passed parameter is an instance of ",(0,t.jsx)(r.code,{children:"Error"})," which has the ",(0,t.jsx)(r.code,{children:"code"})," property. All errors thrown by the picker and viewer modules have the ",(0,t.jsx)(r.code,{children:"code"})," property, which contains a value from ",(0,t.jsx)(r.a,{href:"#error-codes",children:(0,t.jsx)(r.code,{children:"errorCodes"})})," or some other string for the less-usual errors."]}),"\n",(0,t.jsxs)(r.p,{children:[(0,t.jsx)(r.code,{children:"isErrorWithCode"})," can be used to avoid ",(0,t.jsx)(r.code,{children:"as"})," casting when you want to access the ",(0,t.jsx)(r.code,{children:"code"})," property on errors returned by the module."]}),"\n",(0,t.jsx)(r.pre,{children:(0,t.jsx)(r.code,{className:"language-ts",children:"import { pick, isErrorWithCode } from '@vonovak/react-native-document-picker'\n\ntry {\n  const [pickResult] = await pick()\n  // do something with pickResult\n} catch (error) {\n  if (isErrorWithCode(error)) {\n    // here you can safely read `error.code` and TypeScript will know that it has a value\n  } else {\n    // this error does not have a `code`, and does not come from the native module\n  }\n}\n"})}),"\n",(0,t.jsx)(r.h3,{id:"error-codes",children:"Error codes"}),"\n",(0,t.jsxs)(r.p,{children:["Both ",(0,t.jsx)(r.code,{children:"react-native-document-picker"})," and ",(0,t.jsx)(r.code,{children:"react-native-document-viewer"})," expose a ",(0,t.jsx)(r.code,{children:"errorCodes"})," object which contains a list of possible error codes that can be returned by the native module."]}),"\n",(0,t.jsx)(r.pre,{children:(0,t.jsx)(r.code,{className:"language-ts",children:"import { errorCodes } from '@vonovak/react-native-document-picker'\nimport { errorCodes } from '@vonovak/react-native-document-viewer'\n"})}),"\n",(0,t.jsx)(r.p,{children:"Error codes are useful when determining which kind of error has occurred during the picking or viewing process."}),"\n",(0,t.jsxs)(r.table,{children:[(0,t.jsx)(r.thead,{children:(0,t.jsxs)(r.tr,{children:[(0,t.jsx)(r.th,{children:"Error Code Key"}),(0,t.jsx)(r.th,{children:"Description"})]})}),(0,t.jsxs)(r.tbody,{children:[(0,t.jsxs)(r.tr,{children:[(0,t.jsx)(r.td,{children:(0,t.jsx)(r.code,{children:"OPERATION_CANCELED"})}),(0,t.jsx)(r.td,{children:"When user cancels the operation"})]}),(0,t.jsxs)(r.tr,{children:[(0,t.jsx)(r.td,{children:(0,t.jsx)(r.code,{children:"IN_PROGRESS"})}),(0,t.jsxs)(r.td,{children:["This is rather a warning, that happens when you invoke an operation (e.g. ",(0,t.jsx)(r.code,{children:"pick"}),") while a previous one has not finished yet. For example: if you call ",(0,t.jsx)(r.code,{children:"pick()"})," quickly twice in a row, 2 calls to ",(0,t.jsx)(r.code,{children:"pick()"})," in the native module will be done. The first call will open the native document picker and user action will be expected. The promise from the second call to ",(0,t.jsx)(r.code,{children:"pick"}),' will be rejected with this error. Later, the first promise will resolve (or reject) with the actual files that the user has selected. Only one document picker window will be presented to the user. The reason the module explicitely rejects "duplicated" calls is to avoid memory leaks.']})]}),(0,t.jsxs)(r.tr,{children:[(0,t.jsx)(r.td,{children:(0,t.jsx)(r.code,{children:"UNABLE_TO_OPEN_FILE_TYPE"})}),(0,t.jsxs)(r.td,{children:["When you try to open picker or viewer using configuration that system cannot comply with. On Android, this is corresponds to ",(0,t.jsx)(r.a,{href:"https://developer.android.com/reference/android/content/ActivityNotFoundException",children:"ActivityNotFoundException"}),". On iOS this only happens in the Viewer module when you attempt to preview a file that's not suppored by the ",(0,t.jsx)(r.a,{href:"https://developer.apple.com/documentation/quicklook",children:"QuickLook framework"}),"."]})]})]})]})]})}function l(e={}){const{wrapper:r}={...(0,n.a)(),...e.components};return r?(0,t.jsx)(r,{...e,children:(0,t.jsx)(h,{...e})}):h(e)}},1151:(e,r,o)=>{o.d(r,{Z:()=>c,a:()=>s});var t=o(7294);const n={},i=t.createContext(n);function s(e){const r=t.useContext(i);return t.useMemo((function(){return"function"==typeof e?e(r):{...r,...e}}),[r,e])}function c(e){let r;return r=e.disableParentContext?"function"==typeof e.components?e.components(n):e.components||n:s(e.components),t.createElement(i.Provider,{value:r},e.children)}}}]);